
# This file was @generated by crate2nix 0.7.1 with the command:
#   "generate" "--cargo-toml" "challenge-bypass-ristretto-ffi/Cargo.toml" "-o" "generated-challenge-bypass-ristretto.nix"
# See https://github.com/kolloch/crate2nix for more info.

{ pkgs ? import <nixpkgs> { config = {}; }
, lib ? pkgs.lib
, stdenv ? pkgs.stdenv
, buildRustCrate ? pkgs.buildRustCrate
  # This is used as the `crateOverrides` argument for `buildRustCrate`.
, defaultCrateOverrides ? pkgs.defaultCrateOverrides
  # The features to enable for the root_crate or the workspace_members.
, rootFeatures ? [ "default" ]
  # If true, throw errors instead of issueing deprecation warnings.
, strictDeprecation ? false
}:

rec {
  #
  # "public" attributes that we attempt to keep stable with new versions of crate2nix.
  #

  rootCrate = rec {
    packageId = "challenge-bypass-ristretto-ffi 1.0.0-pre.1 (path+file:///home/exarkun/Work/PrivateStorage/python-challenge-bypass-ristretto/challenge-bypass-ristretto-ffi)";

    # Use this attribute to refer to the derivation building your root crate package.
    # You can override the features with rootCrate.build.override { features = [ "default" "feature1" ... ]; }.
    build = internal.buildRustCrateWithFeatures {
      inherit packageId;
    };

    # Debug support which might change between releases.
    # File a bug if you depend on any for non-debug work!
    debug = internal.debugCrate { inherit packageId; };
  };
  root_crate =
    internal.deprecationWarning
      "root_crate is deprecated since crate2nix 0.4. Please use rootCrate instead."
      rootCrate.build;
  # Refer your crate build derivation by name here.
  # You can override the features with
  # workspaceMembers."${crateName}".build.override { features = [ "default" "feature1" ... ]; }.
  workspaceMembers = {
    "challenge-bypass-ristretto-ffi" = rec {
      packageId = "challenge-bypass-ristretto-ffi 1.0.0-pre.1 (path+file:///home/exarkun/Work/PrivateStorage/python-challenge-bypass-ristretto/challenge-bypass-ristretto-ffi)";
      build = internal.buildRustCrateWithFeatures {
        packageId = "challenge-bypass-ristretto-ffi 1.0.0-pre.1 (path+file:///home/exarkun/Work/PrivateStorage/python-challenge-bypass-ristretto/challenge-bypass-ristretto-ffi)";
      };

      # Debug support which might change between releases.
      # File a bug if you depend on any for non-debug work!
      debug = internal.debugCrate { inherit packageId; };
    };
  };
  workspace_members =
    internal.deprecationWarning
      "workspace_members is deprecated in crate2nix 0.4. Please use workspaceMembers instead."
      lib.mapAttrs (n: v: v.build) workspaceMembers;

  #
  # "internal" ("private") attributes that may change in every new version of crate2nix.
  #

  internal = rec {
    # Build and dependency information for crates.
    # Many of the fields are passed one-to-one to buildRustCrate.
    #
    # Noteworthy:
    # * `crateBin = [{name = ","; path = ",";}];`: a hack to disable building the binary.
    # * `dependencies`/`buildDependencies`: similar to the corresponding fields for buildRustCrate.
    #   but with additional information which is used during dependency/feature resolution.
    # * `resolvedDependencies`: the selected default features reported by cargo - only included for debugging.
    # * `devDependencies` as of now not used by `buildRustCrate` but used to
    #   inject test dependencies into the build

    crates = {
      "autocfg 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "autocfg";
        version = "0.1.1";
        edition = "2015";
        sha256 = "09s7azy42g6vrvnbmzbb3lm1mrgbpyi28znwigxp7581gbgk8psf";
        authors = [
          "Josh Stone <cuviper@gmail.com>"
        ];

      };
      "base64 0.9.3 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "base64";
        version = "0.9.3";
        edition = "2015";
        sha256 = "0hs62r35bgxslawyrn1vp9rmvrkkm76fqv0vqcwd048vs876r7a8";
        authors = [
          "Alice Maz <alice@alicemaz.com>"
          "Marshall Pierce <marshall@mpierce.org>"
        ];
        dependencies = [
          {
            name = "byteorder";
            packageId = "byteorder 1.2.7 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "safemem";
            packageId = "safemem 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];

      };
      "bitflags 1.0.4 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "bitflags";
        version = "1.0.4";
        edition = "2015";
        sha256 = "04nfhscc9mxwhmai5xgwh4q458rjszmwsvkpf752g1j6dyklg012";
        authors = [
          "The Rust Project Developers"
        ];
        features = {
        };
        resolvedDefaultFeatures = [ "default" ];
      };
      "block-buffer 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "block-buffer";
        version = "0.7.0";
        edition = "2015";
        sha256 = "03fnf1c4k2rpin05dggfmgqrylqvx5ikfpgs65sqa077w1i5qrj9";
        authors = [
          "RustCrypto Developers"
        ];
        dependencies = [
          {
            name = "block-padding";
            packageId = "block-padding 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "byte-tools";
            packageId = "byte-tools 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "byteorder";
            packageId = "byteorder 1.2.7 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
          {
            name = "generic-array";
            packageId = "generic-array 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];

      };
      "block-padding 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "block-padding";
        version = "0.1.2";
        edition = "2015";
        sha256 = "18wf0qig0c46ad9v66vpn2pya0r61p87y6fhfnbvyi730s1kbi2g";
        authors = [
          "RustCrypto Developers"
        ];
        dependencies = [
          {
            name = "byte-tools";
            packageId = "byte-tools 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];

      };
      "byte-tools 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "byte-tools";
        version = "0.3.0";
        edition = "2015";
        sha256 = "10i1pmgcn3p1kym5x72pww195sdlcq6mhisdnpglccp2zpk7j14q";
        authors = [
          "RustCrypto Developers"
        ];

      };
      "byteorder 1.2.7 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "byteorder";
        version = "1.2.7";
        edition = "2015";
        sha256 = "0pgpxnfcsg1s7chdkpbigzl304yc2rbhzar2r6npnh957br8vy4l";
        authors = [
          "Andrew Gallant <jamslam@gmail.com>"
        ];
        features = {
          "default" = [ "std" ];
        };
        resolvedDefaultFeatures = [ "default" "i128" "std" ];
      };
      "cc 1.0.28 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "cc";
        version = "1.0.28";
        edition = "2015";
        # Hack to suppress building binaries
        crateBin = [ { name = ","; path = ","; } ];
        sha256 = "0jgpzik1wr9jgzgnadq3j9s2qi8x5x5wiiw7x8372ndlbiqqnjmv";
        authors = [
          "Alex Crichton <alex@alexcrichton.com>"
        ];
        features = {
          "parallel" = [ "rayon" ];
        };
      };
      "challenge-bypass-ristretto 1.0.0-pre.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "challenge-bypass-ristretto";
        version = "1.0.0-pre.0";
        edition = "2015";
        sha256 = "0drzwr06x4czlx6r8ahkrqn8iss8cz8vsx2jada0ar78nxy0z29q";
        authors = [
          "eV <ev@7pr.xyz>"
        ];
        dependencies = [
          {
            name = "base64";
            packageId = "base64 0.9.3 (registry+https://github.com/rust-lang/crates.io-index)";
            optional = true;
          }
          {
            name = "clear_on_drop";
            packageId = "clear_on_drop 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "crypto-mac";
            packageId = "crypto-mac 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "curve25519-dalek";
            packageId = "curve25519-dalek 1.0.1 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
          {
            name = "digest";
            packageId = "digest 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "hmac";
            packageId = "hmac 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "rand";
            packageId = "rand 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
          {
            name = "rand_chacha";
            packageId = "rand_chacha 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];
        devDependencies = [
          {
            name = "base64";
            packageId = "base64 0.9.3 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];
        features = {
          "alloc" = [ "curve25519-dalek/alloc" ];
          "avx2_backend" = [ "curve25519-dalek/avx2_backend" ];
          "default" = [ "std" "u64_backend" ];
          "nightly" = [ "clear_on_drop/nightly" "curve25519-dalek/nightly" ];
          "std" = [ "alloc" "curve25519-dalek/std" ];
          "u32_backend" = [ "curve25519-dalek/u32_backend" ];
          "u64_backend" = [ "curve25519-dalek/u64_backend" ];
        };
        resolvedDefaultFeatures = [ "alloc" "base64" "default" "nightly" "std" "u64_backend" ];
      };
      "challenge-bypass-ristretto-ffi 1.0.0-pre.1 (path+file:///home/exarkun/Work/PrivateStorage/python-challenge-bypass-ristretto/challenge-bypass-ristretto-ffi)" = rec {
        crateName = "challenge-bypass-ristretto-ffi";
        version = "1.0.0-pre.1";
        edition = "2015";
        src = pkgs.fetchFromGitHub {
          owner = "brave-intl";
          repo = "challenge-bypass-ristretto-ffi";
          rev = "f88d942ddfaf61a4a6703355a77c4ef71bc95c35";
          sha256 = "1gf7ki3q6d15bq71z8s3pc5l2rsp1zk5bqviqlwq7czg674g7zw2";
        };
        type = [ "cdylib" "staticlib" ];
        authors = [
          "eV <ev@7pr.xyz>"
        ];
        dependencies = [
          {
            name = "base64";
            packageId = "base64 0.9.3 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "challenge-bypass-ristretto";
            packageId = "challenge-bypass-ristretto 1.0.0-pre.0 (registry+https://github.com/rust-lang/crates.io-index)";
            features = [ "base64" ];
          }
          {
            name = "hmac";
            packageId = "hmac 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "rand";
            packageId = "rand 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "sha2";
            packageId = "sha2 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];
        features = {
          "nightly" = [ "challenge-bypass-ristretto/nightly" ];
        };
        resolvedDefaultFeatures = [ "cbindgen" "nightly" ];
      };
      "clear_on_drop 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "clear_on_drop";
        version = "0.2.3";
        edition = "2015";
        sha256 = "05qxifm7pkms9gnvr50j67x59m3br5fg68yfcrmv9zr7w40nh9wp";
        authors = [
          "Cesar Eduardo Barros <cesarb@cesarb.eti.br>"
        ];
        buildDependencies = [
          {
            name = "cc";
            packageId = "cc 1.0.28 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];
        features = {
          "nightly" = [ "no_cc" ];
        };
        resolvedDefaultFeatures = [ "nightly" "no_cc" ];
      };
      "cloudabi 0.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "cloudabi";
        version = "0.0.3";
        edition = "2015";
        sha256 = "0kxcg83jlihy0phnd2g8c2c303px3l2p3pkjz357ll6llnd5pz6x";
        libPath = "cloudabi.rs";
        authors = [
          "Nuxi (https://nuxi.nl/) and contributors"
        ];
        dependencies = [
          {
            name = "bitflags";
            packageId = "bitflags 1.0.4 (registry+https://github.com/rust-lang/crates.io-index)";
            optional = true;
          }
        ];
        features = {
          "default" = [ "bitflags" ];
        };
        resolvedDefaultFeatures = [ "bitflags" "default" ];
      };
      "crypto-mac 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "crypto-mac";
        version = "0.7.0";
        edition = "2015";
        sha256 = "1rbrq6qy9dl0pj4ym2zy33miaaa8vpzdss60p9bdb58xy46l0d24";
        authors = [
          "RustCrypto Developers"
        ];
        dependencies = [
          {
            name = "generic-array";
            packageId = "generic-array 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "subtle";
            packageId = "subtle 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "dev" = [ "blobby" ];
        };
      };
      "curve25519-dalek 1.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "curve25519-dalek";
        version = "1.0.1";
        edition = "2015";
        sha256 = "0s8klqhfwyzpgh0g1n5r7wnmaany8z3qg8cz53hxnv6blgcl9jbq";
        authors = [
          "Isis Lovecruft <isis@patternsinthevoid.net>"
          "Henry de Valence <hdevalence@hdevalence.ca>"
        ];
        dependencies = [
          {
            name = "byteorder";
            packageId = "byteorder 1.2.7 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
            features = [ "i128" ];
          }
          {
            name = "clear_on_drop";
            packageId = "clear_on_drop 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "digest";
            packageId = "digest 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
          {
            name = "rand";
            packageId = "rand 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
          {
            name = "subtle";
            packageId = "subtle 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
        ];
        buildDependencies = [
          {
            name = "byteorder";
            packageId = "byteorder 1.2.7 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
            features = [ "i128" ];
          }
          {
            name = "clear_on_drop";
            packageId = "clear_on_drop 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "digest";
            packageId = "digest 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
          {
            name = "rand";
            packageId = "rand 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
          {
            name = "subtle";
            packageId = "subtle 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "avx2_backend" = [ "nightly" "u64_backend" "packed_simd" ];
          "default" = [ "std" "u64_backend" ];
          "nightly" = [ "subtle/nightly" "clear_on_drop/nightly" ];
          "std" = [ "alloc" "subtle/std" "rand/std" ];
        };
        resolvedDefaultFeatures = [ "alloc" "nightly" "std" "u64_backend" ];
      };
      "digest 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "digest";
        version = "0.8.0";
        edition = "2015";
        sha256 = "0p0kxsb6b2qgc8d28dzvppmwmnx7h77cf8hf05idhfjdk1k77x05";
        authors = [
          "RustCrypto Developers"
        ];
        dependencies = [
          {
            name = "generic-array";
            packageId = "generic-array 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];
        features = {
          "dev" = [ "blobby" ];
        };
        resolvedDefaultFeatures = [ "std" ];
      };
      "fake-simd 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "fake-simd";
        version = "0.1.2";
        edition = "2015";
        sha256 = "1vfylvk4va2ivqx85603lyqqp0zk52cgbs4n5nfbbbqx577qm2p8";
        authors = [
          "The Rust-Crypto Project Developers"
        ];

      };
      "fuchsia-zircon 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "fuchsia-zircon";
        version = "0.3.3";
        edition = "2015";
        sha256 = "10jxc5ks1x06gpd0xg51kcjrxr35nj6qhx2zlc5n7bmskv3675rf";
        authors = [
          "Raph Levien <raph@google.com>"
        ];
        dependencies = [
          {
            name = "bitflags";
            packageId = "bitflags 1.0.4 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "fuchsia-zircon-sys";
            packageId = "fuchsia-zircon-sys 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];

      };
      "fuchsia-zircon-sys 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "fuchsia-zircon-sys";
        version = "0.3.3";
        edition = "2015";
        sha256 = "19zp2085qsyq2bh1gvcxq1lb8w6v6jj9kbdkhpdjrl95fypakjix";
        authors = [
          "Raph Levien <raph@google.com>"
        ];

      };
      "generic-array 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "generic-array";
        version = "0.12.0";
        edition = "2015";
        sha256 = "14lmhgcspg7zjv43sd1q6xlh12f1lwnpli5gfl0rdddzyp12h3rw";
        libName = "generic_array";
        authors = [
          "Bartłomiej Kamiński <fizyk20@gmail.com>"
          "Aaron Trent <novacrazy@gmail.com>"
        ];
        dependencies = [
          {
            name = "typenum";
            packageId = "typenum 1.10.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];

      };
      "hmac 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "hmac";
        version = "0.7.0";
        edition = "2015";
        sha256 = "0wcph449jmnm3kiryzqxf9wkqdnkal9gg1jz684g4s9mcc4aj9zi";
        authors = [
          "RustCrypto Developers"
        ];
        dependencies = [
          {
            name = "crypto-mac";
            packageId = "crypto-mac 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "digest";
            packageId = "digest 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];
        devDependencies = [
          {
            name = "crypto-mac";
            packageId = "crypto-mac 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)";
            features = [ "dev" ];
          }
        ];

      };
      "libc 0.2.46 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "libc";
        version = "0.2.46";
        edition = "2015";
        sha256 = "1gdx3dd1l0y785l4k633k2vr8m9ib8a386acfgwrbxigkg84qfh2";
        authors = [
          "The Rust Project Developers"
        ];
        features = {
          "default" = [ "use_std" ];
          "rustc-dep-of-std" = [ "align" "rustc-std-workspace-core" ];
        };
        resolvedDefaultFeatures = [ "default" "use_std" ];
      };
      "opaque-debug 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "opaque-debug";
        version = "0.2.1";
        edition = "2015";
        sha256 = "10k6vlrrzgg1xs3fpcpaccwbd07klym5is3g8mnjbgg146wbrv2i";
        authors = [
          "RustCrypto Developers"
        ];

      };
      "rand 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "rand";
        version = "0.6.4";
        edition = "2015";
        sha256 = "1dcnmlf49hihn8mwkj274xz4vwkkwjl3z5y2nanbqv5ch0z501ir";
        authors = [
          "The Rand Project Developers"
          "The Rust Project Developers"
        ];
        dependencies = [
          {
            name = "libc";
            packageId = "libc 0.2.46 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
            target = { target, features }: target."unix";
          }
          {
            name = "rand_chacha";
            packageId = "rand_chacha 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "rand_core";
            packageId = "rand_core 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
          {
            name = "rand_hc";
            packageId = "rand_hc 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "rand_isaac";
            packageId = "rand_isaac 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "rand_os";
            packageId = "rand_os 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)";
            optional = true;
          }
          {
            name = "rand_pcg";
            packageId = "rand_pcg 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "rand_xorshift";
            packageId = "rand_xorshift 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "winapi";
            packageId = "winapi 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)";
            target = { target, features }: target."windows";
            features = [ "minwindef" "ntsecapi" "profileapi" "winnt" ];
          }
        ];
        buildDependencies = [
          {
            name = "autocfg";
            packageId = "autocfg 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];
        features = {
          "alloc" = [ "rand_core/alloc" ];
          "default" = [ "std" "rand_os" ];
          "nightly" = [ "simd_support" ];
          "serde1" = [ "rand_core/serde1" "rand_isaac/serde1" "rand_xorshift/serde1" ];
          "simd_support" = [ "packed_simd" ];
          "std" = [ "rand_core/std" "alloc" "rand_os" ];
          "stdweb" = [ "rand_os/stdweb" ];
          "wasm-bindgen" = [ "rand_os/wasm-bindgen" ];
        };
        resolvedDefaultFeatures = [ "alloc" "default" "rand_os" "std" ];
      };
      "rand_chacha 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "rand_chacha";
        version = "0.1.1";
        edition = "2015";
        sha256 = "1vxwyzs4fy1ffjc8l00fsyygpiss135irjf7nyxgq2v0lqf3lvam";
        authors = [
          "The Rand Project Developers"
          "The Rust Project Developers"
        ];
        dependencies = [
          {
            name = "rand_core";
            packageId = "rand_core 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
        ];
        buildDependencies = [
          {
            name = "autocfg";
            packageId = "autocfg 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];

      };
      "rand_core 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "rand_core";
        version = "0.3.0";
        edition = "2015";
        sha256 = "1ny668mv568q7ym8qrkwv6gvf7lkyq0qfx2c9lqkpiwy0yvvc189";
        authors = [
          "The Rust Project Developers"
        ];
        features = {
          "default" = [ "std" ];
          "serde1" = [ "serde" "serde_derive" ];
          "std" = [ "alloc" ];
        };
        resolvedDefaultFeatures = [ "alloc" "std" ];
      };
      "rand_hc 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "rand_hc";
        version = "0.1.0";
        edition = "2015";
        sha256 = "1i0vl8q5ddvvy0x8hf1zxny393miyzxkwqnw31ifg6p0gdy6fh3v";
        authors = [
          "The Rand Project Developers"
        ];
        dependencies = [
          {
            name = "rand_core";
            packageId = "rand_core 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
        ];

      };
      "rand_isaac 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "rand_isaac";
        version = "0.1.1";
        edition = "2015";
        sha256 = "027flpjr4znx2csxk7gxb7vrf9c7y5mydmvg5az2afgisp4rgnfy";
        authors = [
          "The Rand Project Developers"
          "The Rust Project Developers"
        ];
        dependencies = [
          {
            name = "rand_core";
            packageId = "rand_core 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "serde1" = [ "serde" "serde_derive" "rand_core/serde1" ];
        };
      };
      "rand_os 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "rand_os";
        version = "0.1.1";
        edition = "2015";
        sha256 = "1jpysx8ax3vp4x0b84cgxfdsy7bmfccdvx9h4w65pxxca1avsvzl";
        authors = [
          "The Rand Project Developers"
        ];
        dependencies = [
          {
            name = "cloudabi";
            packageId = "cloudabi 0.0.3 (registry+https://github.com/rust-lang/crates.io-index)";
            target = { target, features }: (target."os" == "cloudabi");
          }
          {
            name = "fuchsia-zircon";
            packageId = "fuchsia-zircon 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)";
            target = { target, features }: (target."os" == "fuchsia");
          }
          {
            name = "libc";
            packageId = "libc 0.2.46 (registry+https://github.com/rust-lang/crates.io-index)";
            target = { target, features }: target."unix";
          }
          {
            name = "rand_core";
            packageId = "rand_core 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
          {
            name = "rdrand";
            packageId = "rdrand 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)";
            target = { target, features }: (target."env" == "sgx");
          }
          {
            name = "winapi";
            packageId = "winapi 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)";
            target = { target, features }: target."windows";
            features = [ "minwindef" "ntsecapi" "winnt" ];
          }
        ];

      };
      "rand_pcg 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "rand_pcg";
        version = "0.1.1";
        edition = "2015";
        sha256 = "01gy6ad7bpj5ymshfnz9m4cz3rv0bbgbvma4pdb4w1676fdd0sq8";
        authors = [
          "The Rand Project Developers"
        ];
        dependencies = [
          {
            name = "rand_core";
            packageId = "rand_core 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
        ];
        buildDependencies = [
          {
            name = "rustc_version";
            packageId = "rustc_version 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];
        features = {
          "serde1" = [ "serde" "serde_derive" "bincode/i128" ];
        };
      };
      "rand_xorshift 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "rand_xorshift";
        version = "0.1.1";
        edition = "2015";
        sha256 = "0p2x8nr00hricpi2m6ca5vysiha7ybnghz79yqhhx6sl4gkfkxyb";
        authors = [
          "The Rand Project Developers"
          "The Rust Project Developers"
        ];
        dependencies = [
          {
            name = "rand_core";
            packageId = "rand_core 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "serde1" = [ "serde" "serde_derive" ];
        };
      };
      "rdrand 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "rdrand";
        version = "0.4.0";
        edition = "2015";
        sha256 = "1cjq0kwx1bk7jx3kzyciiish5gqsj7620dm43dc52sr8fzmm9037";
        authors = [
          "Simonas Kazlauskas <rdrand@kazlauskas.me>"
        ];
        dependencies = [
          {
            name = "rand_core";
            packageId = "rand_core 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)";
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "default" = [ "std" ];
        };
        resolvedDefaultFeatures = [ "default" "std" ];
      };
      "rustc_version 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "rustc_version";
        version = "0.2.3";
        edition = "2015";
        sha256 = "02h3x57lcr8l2pm0a645s9whdh33pn5cnrwvn5cb57vcrc53x3hk";
        authors = [
          "Marvin Löbel <loebel.marvin@gmail.com>"
        ];
        dependencies = [
          {
            name = "semver";
            packageId = "semver 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];

      };
      "safemem 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "safemem";
        version = "0.3.0";
        edition = "2015";
        sha256 = "1n9xm7hbh7k2xjbzp2ggpxhlmrdln3idzk1nkrsb0v5990r4bjld";
        authors = [
          "Austin Bonander <austin.bonander@gmail.com>"
        ];
        features = {
          "default" = [ "std" ];
        };
        resolvedDefaultFeatures = [ "default" "std" ];
      };
      "semver 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "semver";
        version = "0.9.0";
        edition = "2015";
        sha256 = "00q4lkcj0rrgbhviv9sd4p6qmdsipkwkbra7rh11jrhq5kpvjzhx";
        authors = [
          "Steve Klabnik <steve@steveklabnik.com>"
          "The Rust Project Developers"
        ];
        dependencies = [
          {
            name = "semver-parser";
            packageId = "semver-parser 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];
        features = {
          "ci" = [ "serde" ];
        };
        resolvedDefaultFeatures = [ "default" ];
      };
      "semver-parser 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "semver-parser";
        version = "0.7.0";
        edition = "2015";
        sha256 = "18vhypw6zgccnrlm5ps1pwa0khz7ry927iznpr88b87cagr1v2iq";
        authors = [
          "Steve Klabnik <steve@steveklabnik.com>"
        ];

      };
      "sha2 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "sha2";
        version = "0.8.0";
        edition = "2015";
        sha256 = "0gal773gz8gkpa9rndc917z6rl9kzd8q8gapaxv437s61vyqnkbv";
        authors = [
          "RustCrypto Developers"
        ];
        dependencies = [
          {
            name = "block-buffer";
            packageId = "block-buffer 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "digest";
            packageId = "digest 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "fake-simd";
            packageId = "fake-simd 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)";
          }
          {
            name = "opaque-debug";
            packageId = "opaque-debug 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)";
          }
        ];
        devDependencies = [
          {
            name = "digest";
            packageId = "digest 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)";
            features = [ "dev" ];
          }
        ];
        features = {
          "asm" = [ "sha2-asm" ];
          "default" = [ "std" ];
          "std" = [ "digest/std" ];
        };
        resolvedDefaultFeatures = [ "default" "std" ];
      };
      "subtle 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "subtle";
        version = "1.0.0";
        edition = "2015";
        sha256 = "1vm80mxbwfj334izwm8x8l65v1xl9hr0kwrg36r1rq565fkaarrd";
        authors = [
          "Isis Lovecruft <isis@patternsinthevoid.net>"
          "Henry de Valence <hdevalence@hdevalence.ca>"
        ];
        features = {
          "default" = [ "std" "i128" ];
        };
      };
      "subtle 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "subtle";
        version = "2.0.0";
        edition = "2015";
        sha256 = "09nr433vny879q2vna1xcsxvdqbyf3rvnbyfci5bgpix5x8n49kh";
        authors = [
          "Isis Lovecruft <isis@patternsinthevoid.net>"
          "Henry de Valence <hdevalence@hdevalence.ca>"
        ];
        features = {
          "default" = [ "std" "i128" ];
        };
        resolvedDefaultFeatures = [ "nightly" "std" ];
      };
      "typenum 1.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "typenum";
        version = "1.10.0";
        edition = "2015";
        sha256 = "0sc1jirllfhdi52z1xv9yqzxzpk6v7vadd13n7wvs1wnjipn6bb1";
        build = "build/main.rs";
        authors = [
          "Paho Lurie-Gregg <paho@paholg.com>"
          "Andre Bogus <bogusandre@gmail.com>"
        ];
        features = {
        };
      };
      "winapi 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "winapi";
        version = "0.3.6";
        edition = "2015";
        sha256 = "1c6479gvfz8iqnrlicqcn5b5rgjpmnn241aa47x6q9qychryphcj";
        authors = [
          "Peter Atashian <retep998@gmail.com>"
        ];
        dependencies = [
          {
            name = "winapi-i686-pc-windows-gnu";
            packageId = "winapi-i686-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)";
            target = { target, features }: (stdenv.hostPlatform.config == "i686-pc-windows-gnu");
          }
          {
            name = "winapi-x86_64-pc-windows-gnu";
            packageId = "winapi-x86_64-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)";
            target = { target, features }: (stdenv.hostPlatform.config == "x86_64-pc-windows-gnu");
          }
        ];
        features = {
        };
        resolvedDefaultFeatures = [ "minwindef" "ntsecapi" "profileapi" "winnt" ];
      };
      "winapi-i686-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "winapi-i686-pc-windows-gnu";
        version = "0.4.0";
        edition = "2015";
        sha256 = "1dmpa6mvcvzz16zg6d5vrfy4bxgg541wxrcip7cnshi06v38ffxc";
        authors = [
          "Peter Atashian <retep998@gmail.com>"
        ];

      };
      "winapi-x86_64-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
        crateName = "winapi-x86_64-pc-windows-gnu";
        version = "0.4.0";
        edition = "2015";
        sha256 = "0gqq64czqb64kskjryj8isp62m2sgvx25yyj3kpc2myh85w24bki";
        authors = [
          "Peter Atashian <retep998@gmail.com>"
        ];

      };
    };

    #
# crate2nix/default.nix (excerpt start)
#

  /* Target (platform) data for conditional dependencies.
     This corresponds roughly to what buildRustCrate is setting.
  */
  defaultTarget = {
    unix = true;
    windows = false;
    fuchsia = true;
    test = false;

    # This doesn't appear to be officially documented anywhere yet.
    # See https://github.com/rust-lang-nursery/rust-forge/issues/101.
    os = if stdenv.hostPlatform.isDarwin
    then "macos"
    else stdenv.hostPlatform.parsed.kernel.name;
    arch = stdenv.hostPlatform.parsed.cpu.name;
    family = "unix";
    env = "gnu";
    endian =
      if stdenv.hostPlatform.parsed.cpu.significantByte.name == "littleEndian"
      then "little" else "big";
    pointer_width = toString stdenv.hostPlatform.parsed.cpu.bits;
    vendor = stdenv.hostPlatform.parsed.vendor.name;
    debug_assertions = false;
  };

  /* Filters common temp files and build files. */
  # TODO(pkolloch): Substitute with gitignore filter
  sourceFilter = name: type:
    let
      baseName = builtins.baseNameOf (builtins.toString name);
    in
      ! (
        # Filter out git
        baseName == ".gitignore"
        || (type == "directory" && baseName == ".git")

        # Filter out build results
        || (
          type == "directory" && (
            baseName == "target"
            || baseName == "_site"
            || baseName == ".sass-cache"
            || baseName == ".jekyll-metadata"
            || baseName == "build-artifacts"
          )
        )

        # Filter out nix-build result symlinks
        || (
          type == "symlink" && lib.hasPrefix "result" baseName
        )

        # Filter out IDE config
        || (
          type == "directory" && (
            baseName == ".idea" || baseName == ".vscode"
          )
        ) || lib.hasSuffix ".iml" baseName

        # Filter out nix build files
        || baseName == "Cargo.nix"

        # Filter out editor backup / swap files.
        || lib.hasSuffix "~" baseName
        || builtins.match "^\\.sw[a-z]$$" baseName != null
        || builtins.match "^\\..*\\.sw[a-z]$$" baseName != null
        || lib.hasSuffix ".tmp" baseName
        || lib.hasSuffix ".bak" baseName
        || baseName == "tests.nix"
      );

  /* Returns a crate which depends on successful test execution
     of crate given as the second argument.
  */
  crateWithTest = crate: testCrate: testCrateFlags:
    let
      # override the `crate` so that it will build and execute tests instead of
      # building the actual lib and bin targets We just have to pass `--test`
      # to rustc and it will do the right thing.  We execute the tests and copy
      # their log and the test executables to $out for later inspection.
      test = let
        drv = testCrate.override (
          _: {
            buildTests = true;
          }
        );
      in
        pkgs.runCommand "run-tests-${testCrate.name}" {
          inherit testCrateFlags;
        } ''
          set -ex
          cd ${crate.src}
          for file in ${drv}/tests/*; do
            $file $testCrateFlags 2>&1 | tee -a $out
          done
        '';
    in
      crate.overrideAttrs (
        old: {
          checkPhase = ''
            test -e ${test}
          '';
          passthru = (old.passthru or {}) // {
            inherit test;
          };
        }
      );

  /* A restricted overridable version of builtRustCratesWithFeatures. */
  buildRustCrateWithFeatures =
    { packageId
    , features ? rootFeatures
    , crateOverrides ? defaultCrateOverrides
    , buildRustCrateFunc ? (
        if crateOverrides == pkgs.defaultCrateOverrides
        then buildRustCrate
        else buildRustCrate.override {
          defaultCrateOverrides = crateOverrides;
        }
      )
    , runTests ? false
    , testCrateFlags ? []
    }:
      lib.makeOverridable
        (
          { features, crateOverrides, runTests, testCrateFlags }:
            let
              builtRustCrates = builtRustCratesWithFeatures {
                inherit packageId features buildRustCrateFunc;
                runTests = false;
              };
              builtTestRustCrates = builtRustCratesWithFeatures {
                inherit packageId features buildRustCrateFunc;
                runTests = true;
              };
              drv = builtRustCrates.${packageId};
              testDrv = builtTestRustCrates.${packageId};
            in
              if runTests then crateWithTest drv testDrv testCrateFlags else drv
        )
        { inherit features crateOverrides runTests testCrateFlags; };

  /* Returns an attr set with packageId mapped to the result of buildRustCrateFunc
     for the corresponding crate.
  */
  builtRustCratesWithFeatures =
    { packageId
    , features
    , crateConfigs ? crates
    , buildRustCrateFunc
    , runTests
    , target ? defaultTarget
    } @ args:
      assert (builtins.isAttrs crateConfigs);
      assert (builtins.isString packageId);
      assert (builtins.isList features);
      assert (builtins.isAttrs target);
      assert (builtins.isBool runTests);

      let
        rootPackageId = packageId;
        mergedFeatures = mergePackageFeatures (
          args // {
            inherit rootPackageId;
            target = target // { test = runTests; };
          }
        );

        buildByPackageId = packageId: buildByPackageIdImpl packageId;

        # Memoize built packages so that reappearing packages are only built once.
        builtByPackageId =
          lib.mapAttrs (packageId: value: buildByPackageId packageId) crateConfigs;

        buildByPackageIdImpl = packageId:
          let
            features = mergedFeatures."${packageId}" or [];
            crateConfig' = crateConfigs."${packageId}";
            crateConfig =
              builtins.removeAttrs crateConfig' [ "resolvedDefaultFeatures" "devDependencies" ];
            devDependencies =
              lib.optionals
                (runTests && packageId == rootPackageId)
                (crateConfig'.devDependencies or []);
            dependencies =
              dependencyDerivations {
                inherit builtByPackageId features target;
                dependencies =
                  (crateConfig.dependencies or [])
                  ++ devDependencies;
              };
            buildDependencies =
              dependencyDerivations {
                inherit builtByPackageId features target;
                dependencies = crateConfig.buildDependencies or [];
              };

            dependenciesWithRenames =
              lib.filter (d: d ? "rename") (
                (crateConfig.buildDependencies or [])
                ++ (crateConfig.dependencies or [])
                ++ devDependencies
              );

            crateRenames =
              builtins.listToAttrs
                (map (d: { name = d.name; value = d.rename; }) dependenciesWithRenames);
          in
            buildRustCrateFunc (
              crateConfig // {
                src = crateConfig.src or (
                  pkgs.fetchurl {
                    name = "${crateConfig.crateName}-${crateConfig.version}.tar.gz";
                    url = "https://crates.io/api/v1/crates/${crateConfig.crateName}/${crateConfig.version}/download";
                    sha256 = crateConfig.sha256;
                  }
                );
                inherit features dependencies buildDependencies crateRenames;
              }
            );
      in
        builtByPackageId;

  /* Returns the actual derivations for the given dependencies. */
  dependencyDerivations =
    { builtByPackageId
    , features
    , dependencies
    , target
    }:
      assert (builtins.isAttrs builtByPackageId);
      assert (builtins.isList features);
      assert (builtins.isList dependencies);
      assert (builtins.isAttrs target);

      let
        enabledDependencies = filterEnabledDependencies {
          inherit dependencies features target;
        };
        depDerivation = dependency: builtByPackageId.${dependency.packageId};
      in
        map depDerivation enabledDependencies;

  /* Returns a sanitized version of val with all values substituted that cannot
     be serialized as JSON.
  */
  sanitizeForJson = val:
    if builtins.isAttrs val
    then lib.mapAttrs (n: v: sanitizeForJson v) val
    else if builtins.isList val
    then builtins.map sanitizeForJson val
    else if builtins.isFunction val
    then "function"
    else val;

  /* Returns various tools to debug a crate. */
  debugCrate = { packageId, target }:
    assert (builtins.isString packageId);

    let
      debug = rec {
        # The built tree as passed to buildRustCrate.
        buildTree = buildRustCrateWithFeatures {
          buildRustCrateFunc = lib.id;
          inherit packageId;
        };
        sanitizedBuildTree = sanitizeForJson buildTree;
        dependencyTree = sanitizeForJson (
          buildRustCrateWithFeatures {
            buildRustCrateFunc = crate: {
              "01_crateName" = crate.crateName or false;
              "02_features" = crate.features or [];
              "03_dependencies" = crate.dependencies or [];
            };
            inherit packageId;
          }
        );
        mergedPackageFeatures = mergePackageFeatures {
          features = rootFeatures;
          inherit packageId target;
        };
        diffedDefaultPackageFeatures = diffDefaultPackageFeatures {
          features = rootFeatures;
          inherit packageId;
        };
      };
    in
      { internal = debug; };

  /* Returns differences between cargo default features and crate2nix default
     features.

     This is useful for verifying the feature resolution in crate2nix.
  */
  diffDefaultPackageFeatures =
    { crateConfigs ? crates
    , packageId
    , target
    }:
      assert (builtins.isAttrs crateConfigs);

      let
        prefixValues = prefix: lib.mapAttrs (n: v: { "${prefix}" = v; });
        mergedFeatures =
          prefixValues
            "crate2nix"
            (mergePackageFeatures { inherit crateConfigs packageId target; features = [ "default" ]; });
        configs = prefixValues "cargo" crateConfigs;
        combined = lib.foldAttrs (a: b: a // b) {} [ mergedFeatures configs ];
        onlyInCargo =
          builtins.attrNames
            (lib.filterAttrs (n: v: !(v ? "crate2nix") && (v ? "cargo")) combined);
        onlyInCrate2Nix =
          builtins.attrNames
            (lib.filterAttrs (n: v: (v ? "crate2nix") && !(v ? "cargo")) combined);
        differentFeatures = lib.filterAttrs
          (
            n: v:
              (v ? "crate2nix")
              && (v ? "cargo")
              && (v.crate2nix.features or []) != (v."cargo".resolved_default_features or [])
          )
          combined;
      in
        builtins.toJSON {
          inherit onlyInCargo onlyInCrate2Nix differentFeatures;
        };

  /* Returns an attrset mapping packageId to the list of enabled features.

     If multiple paths to a dependency enable different features, the
     corresponding feature sets are merged. Features in rust are additive.
  */
  mergePackageFeatures =
    { crateConfigs ? crates
    , packageId
    , rootPackageId ? packageId
    , features ? rootFeatures
    , dependencyPath ? [ crates.${packageId}.crateName ]
    , featuresByPackageId ? {}
    , target
      # Adds devDependencies to the crate with rootPackageId.
    , runTests ? false
    , ...
    } @ args:
      assert (builtins.isAttrs crateConfigs);
      assert (builtins.isString packageId);
      assert (builtins.isString rootPackageId);
      assert (builtins.isList features);
      assert (builtins.isList dependencyPath);
      assert (builtins.isAttrs featuresByPackageId);
      assert (builtins.isAttrs target);
      assert (builtins.isBool runTests);

      let
        crateConfig = crateConfigs."${packageId}" or (builtins.throw "Package not found: ${packageId}");
        expandedFeatures = expandFeatures (crateConfig.features or {}) features;

        depWithResolvedFeatures = dependency:
          let
            packageId = dependency.packageId;
            features = dependencyFeatures expandedFeatures dependency;
          in
            { inherit packageId features; };

        resolveDependencies = cache: path: dependencies:
          assert (builtins.isAttrs cache);
          assert (builtins.isList dependencies);

          let
            enabledDependencies = filterEnabledDependencies {
              inherit dependencies target;
              features = expandedFeatures;
            };
            directDependencies = map depWithResolvedFeatures enabledDependencies;
            foldOverCache = op: lib.foldl op cache directDependencies;
          in
            foldOverCache
              (
                cache: { packageId, features }:
                  let
                    cacheFeatures = cache.${packageId} or [];
                    combinedFeatures = sortedUnique (cacheFeatures ++ features);
                  in
                    if cache ? ${packageId} && cache.${packageId} == combinedFeatures
                    then cache
                    else mergePackageFeatures {
                      features = combinedFeatures;
                      featuresByPackageId = cache;
                      inherit crateConfigs packageId target runTests rootPackageId;
                    }
              );

        cacheWithSelf =
          let
            cacheFeatures = featuresByPackageId.${packageId} or [];
            combinedFeatures = sortedUnique (cacheFeatures ++ expandedFeatures);
          in
            featuresByPackageId // {
              "${packageId}" = combinedFeatures;
            };

        cacheWithDependencies =
          resolveDependencies cacheWithSelf "dep" (
            crateConfig.dependencies or []
            ++ lib.optionals
              (runTests && packageId == rootPackageId)
              (crateConfig.devDependencies or [])
          );

        cacheWithAll =
          resolveDependencies
            cacheWithDependencies "build"
            (crateConfig.buildDependencies or []);

      in
        cacheWithAll;

  /* Returns the enabled dependencies given the enabled features. */
  filterEnabledDependencies = { dependencies, features, target }:
    assert (builtins.isList dependencies);
    assert (builtins.isList features);
    assert (builtins.isAttrs target);

    lib.filter
      (
        dep:
          let
            targetFunc = dep.target or (features: true);
          in
            targetFunc { inherit features target; }
            && (
              !(dep.optional or false)
              || builtins.any (doesFeatureEnableDependency dep) features
            )
      )
      dependencies;

  /* Returns whether the given feature should enable the given dependency. */
  doesFeatureEnableDependency = { name, rename ? null, ... }: feature:
    let
      prefix = "${name}/";
      len = builtins.stringLength prefix;
      startsWithPrefix = builtins.substring 0 len feature == prefix;
    in
      feature == name
      || (rename != null && rename == feature)
      || startsWithPrefix;

  /* Returns the expanded features for the given inputFeatures by applying the
     rules in featureMap.

     featureMap is an attribute set which maps feature names to lists of further
     feature names to enable in case this feature is selected.
  */
  expandFeatures = featureMap: inputFeatures:
    assert (builtins.isAttrs featureMap);
    assert (builtins.isList inputFeatures);

    let
      expandFeature = feature:
        assert (builtins.isString feature);
        [ feature ] ++ (expandFeatures featureMap (featureMap."${feature}" or []));
      outFeatures = builtins.concatMap expandFeature inputFeatures;
    in
      sortedUnique outFeatures;

  /*
     Returns the actual dependencies for the given dependency.

     features: The features of the crate that refers this dependency.
  */
  dependencyFeatures = features: dependency:
    assert (builtins.isList features);
    assert (builtins.isAttrs dependency);

    let
      defaultOrNil = if dependency.usesDefaultFeatures or true
      then [ "default" ]
      else [];
      explicitFeatures = dependency.features or [];
      additionalDependencyFeatures =
        let
          dependencyPrefix = dependency.name + "/";
          dependencyFeatures =
            builtins.filter (f: lib.hasPrefix dependencyPrefix f) features;
        in
          builtins.map (lib.removePrefix dependencyPrefix) dependencyFeatures;
    in
      defaultOrNil ++ explicitFeatures ++ additionalDependencyFeatures;

  /* Sorts and removes duplicates from a list of strings. */
  sortedUnique = features:
    assert (builtins.isList features);
    assert (builtins.all builtins.isString features);

    let
      outFeaturesSet = lib.foldl (set: feature: set // { "${feature}" = 1; }) {} features;
      outFeaturesUnique = builtins.attrNames outFeaturesSet;
    in
      builtins.sort (a: b: a < b) outFeaturesUnique;

  deprecationWarning = message: value:
    if strictDeprecation
    then builtins.throw "strictDeprecation enabled, aborting: ${message}"
    else builtins.trace message value;

  #
  # crate2nix/default.nix (excerpt end)
  #

  };
}
